### ISSUE TITLE
Installation on Windows failing

### ISSUE THREAD

**Issue by KnightCoder** [jagenjo/litefilesystem.js#7]
I am getting the following error when trying to install. 

```
php install.php

 + config.php found, testing database connection
PHP Notice:  Undefined index: folder in D:\Program Files\LiteFilesystem\src\include\modules\files.php on line 26
 + Database connection established
PHP Fatal error:  Uncaught Error: Call to undefined function posix_getgrgid() in D:\Program Files\LiteFilesystem\src\include\modules\system.php:220
Stack trace:
#0 D:\Program Files\LiteFilesystem\src\install.php(143): SystemModule->checkReady()
#1 {main}
  thrown in D:\Program Files\LiteFilesystem\src\include\modules\system.php on line 220
 - Code: 1 "Uncaught Error: Call to undefined function posix_getgrgid() in D:\Program Files\LiteFilesystem\src\include\modules\system.php:220
Stack trace:
#0 D:\Program Files\LiteFilesystem\src\install.php(143): SystemModule->checkReady()
#1 {main}
  thrown" File: D:\Program Files\LiteFilesystem\src\include\modules\system.php Ln: 220

```  
Please help me fix this.

**Comment by liupucn** [comment]
这个问题解决了吗

**Comment by KnightCoder** [comment]
I simply commented this line and so far it doesn't seem to have any issue on windows.

**Comment by atlasan** [comment]
Wrapped that block with
`if (strtoupper(substr(PHP_OS, 0, 3)) != 'WIN'){`
and same for the file install.php Ln: 154

Additionally I added
`if (isset($_REQUEST["folder"]))`
on include\modules\files.php line 26 to solve the last error while calling install.php
